Frontend
dr-naikare/VideoKon_SDK pull request #14
Opened 2024-09-10 18:03 UTC by B-Mustafa

Fix: HomePage Responsiveness

- added drawer for small screens 

![image](https://github.com/user-attachments/assets/474c3297-070c-4e2f-a468-94e74f1d3516)

![image](https://github.com/user-attachments/assets/47c2088f-c520-4414-87d2-4e6d23a1399f)

Add: Lobby Ui 

![image](https://github.com/user-attachments/assets/cc15e5fd-7325-4004-aa28-cb5491fba4d6)

![image](https://github.com/user-attachments/assets/6ce310c4-7987-4ad8-a073-5effd7bc2553)

2024-09-11 06:54 UTC, dr-naikare commented on frontend/src/pages/Lobby.jsx
please improve the layout of the preview video window , make is square rather than rectangle and bring that to left and the input for meeting code to the right like the reference below and also add the 3 select drop down menu below the preview window

<img src="https://github.com/user-attachments/assets/1aa55730-5fee-4bf7-9b17-f0ff9e08ad04" alt="Image" width="400"/>

2024-09-11 06:59 UTC, dr-naikare commented on frontend/src/pages/Meeting.jsx
why did you removed line 150 ?

2024-09-11 07:05 UTC, dr-naikare commented on frontend/package.json
why you have pushed this ?

2024-09-11 07:06 UTC, dr-naikare requested changes
Please check the comments made on #14 and correct that

2024-09-11 07:40 UTC, B-Mustafa commented
I removed line 150 as disconnect is a reserved keyword in socket-io

2024-09-11 11:23 UTC, dr-naikare commented
> I removed line 150 as disconnect is a reserved keyword in socket-io

okay , just comment it out and do the other changes too

2024-09-12 13:11 UTC, B-Mustafa commented
![image](https://github.com/user-attachments/assets/be02cc10-c516-4a16-bb2b-67f5fe96c29c)

there's no need of 3 dots as u can see the previews already by toggling

2024-09-12 13:23 UTC, dr-naikare commented on frontend/src/pages/Lobby.jsx
everything is good , nice work 
just make the lobby page unscrollable and center everythin

2024-09-12 13:23 UTC, dr-naikare requested changes
please make the changes

2024-09-12 14:00 UTC, B-Mustafa commented
![image](https://github.com/user-attachments/assets/8d3d4ecb-7ba4-4cf3-8b54-8b5e7293e5eb)

![image](https://github.com/user-attachments/assets/ad46259f-da13-4a8f-ac19-b4ac1fc22f29)

2024-09-12 14:11 UTC, B-Mustafa commented
![image](https://github.com/user-attachments/assets/e7c176f2-cf13-4dd7-9043-2efcff959b70)

2024-09-12 14:18 UTC, dr-naikare approved these changes
Works well

2024-09-12 14:18 UTC, merged